### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by NB013** [Bouni/abfallplus#1]
Hi
Abfallplus is not available in HACS.
Therefore I tried to install manually and followed the install instructions.

I also implement the part in configuration.yaml, following your example.

AbfallPlus:
    platform: abfallplus
    name: Bio
    key: 5b0384147b5bc055c30fee1fb6db6f76
    municipality: 270
    street: 15720
    trash_ids: 51

Now I get all the time the error ....
The following integrations and platforms could not be set up:

Is my config wrong, or is api.abfallpluss no more up and running.

TX in advance

**Comment by Bouni** [comment]
Hi,

I use the integration myself and it seems to work fine for me.
Would you mind telling me what region you're from or at least tel me the URL of the website of the waste managment of your municipality so I could try to get it working for you?

**Comment by Bouni** [comment]
I just had a quick look an it seems that abfallplus changed there API (which is no official API) and it returns a 404 error.
Hopefully I'll get this fixed asap ...
