### ISSUE TITLE
No longer in Hacs

### ISSUE THREAD

**Issue by Micha031982** [Bouni/abfallplus#2]
Hi,

the repo is no longer available in HACS
Could you make it available again?

Thanks
Michael

**Comment by Bouni** [comment]
Let me check that

**Comment by Bouni** [comment]
To be honest, I think I've never officially submitted this to HACS into the default repo 😅 
You can still add it as a custom repo to HACS and install it that way!

https://hacs.xyz/docs/faq/custom_repositories

**Comment by Bouni** [comment]
Done!

![image](https://user-images.githubusercontent.com/948965/155268387-e19be856-b8e0-4145-a220-0559ab1376cd.png)
