### ISSUE TITLE
How to configure

### ISSUE THREAD

**Issue by Nicras** [Bouni/abfallplus#3]
Hi, 
I was able to get all the IDs and stuff but I can't get the config right. Could you please instruct how to setup this custom component?
Simply adding the yaml code you have on your README won't work.

Thanks a lot

**Comment by Nicras** [comment]
Figured it out...you didn't mention that it is just a sensor. 
;-)
Now it works like a charm

**Comment by Micha031982** [comment]
Hi,
I Also figured it now out with install via HACS
And the Config (all the ID'S)
I'm still not sure how it works i have now a sensor
(blue bracket was a test with set)
![image](https://user-images.githubusercontent.com/19914654/155629944-ae924212-92bc-4039-bd3f-c43ad6611272.png)
The orange is really "Bio" but i can only get it from today
so if i scroll to the future there are no additional entries

Is this how it should work?

**Comment by Bouni** [comment]
@Micha031982 
The sensor has the next collection date for this waset type as it's state, so if its today, you'll see today, if it's in the future, you'll see that as the state.

I've just updated the README.
